services:
  db:
    container_name: mariadb_container
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${DATABASE_CONTAINER_PORT}:${MARIADB_PORT}"
    volumes:
      - /home/db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p ${MARIADB_ROOT_PASSWORD}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build: .
    container_name: user-service
    ports:
      - "${SPRING_CONTAINER_PORT}:${SPRING_CONTAINER_PORT}"
    environment:
      db-url: ${SPRING_DATASOURCE_URL}
      db-username: ${SPRING_DATASOURCE_USERNAME}
      db-password: ${SPRING_DATASOURCE_PASSWORD}
      depends_on: db
      restart: always
