version: "3.8"

services:
  user-service:
    image: amazoncorretto:17
    container_name: user-service
    working_dir: /app

    ports:
      - "${DEV_SPRING_PORT:-8082}:8082"

    env_file: 
      - .env

    volumes:
      - ./target/user_service.jar:/app/user_service.jar

    command: >
      sh -c "
      if [ \"$ACTIVE_PROFILE\" = 'PROD' ]; then
        export SPRING_DATASOURCE_URL=$PROD_SPRING_DATASOURCE_URL &&
        export SPRING_DATASOURCE_USERNAME=$PROD_SPRING_DATASOURCE_USERNAME &&
        export SPRING_DATASOURCE_PASSWORD=$PROD_SPRING_DATASOURCE_PASSWORD &&
        export SERVER_PORT=$PROD_SPRING_PORT;
      else
        export SPRING_DATASOURCE_URL=$DEV_SPRING_DATASOURCE_URL &&
        export SPRING_DATASOURCE_USERNAME=$DEV_SPRING_DATASOURCE_USERNAME &&
        export SPRING_DATASOURCE_PASSWORD=$DEV_SPRING_DATASOURCE_PASSWORD &&
        export SERVER_PORT=$DEV_SPRING_PORT;
      fi &&
      java -jar user_service.jar
      "
