services:
  backend:
    build: .
    container_name: user-service
    ports:
      - "${SPRING_CONTAINER_PORT}:${SPRING_CONTAINER_PORT}"
    environment:
      db-url: ${SPRING_DATASOURCE_URL}
      db-username: ${SPRING_DATASOURCE_USERNAME}
      db-password: ${SPRING_DATASOURCE_PASSWORD}
      restart: always
